// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";
import "./libs/shim/jsonSchema.js";
import{sleep} from 'k6';
export let options = {
  maxRedirects: 4,

  // Smoke + Load profiles
  scenarios: {
    smoke_test: {
      executor: "constant-vus",
      vus: 2,              
      duration: "30s",
      tags: { test_type: "smoke" },
    },

    load_test: {
      executor: "ramping-vus",
      startVUs: 0,
      stages: [
        { duration: "30s", target: 20 }, // ramp-up
        { duration: "2m", target: 50 },  // steady load
        { duration: "30s", target: 0 },  // ramp-down
      ],
      tags: { test_type: "load" },
    },
  },

  
  thresholds: {
    http_req_failed: ["rate<0.01"],     // Error rate < 1%
    http_req_duration: ["p(95)<300"],   // 95% of responses < 800ms
  },
};



const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    baseUrl: "https://dummyjson.com",
    productId: "1"
  }
});

export default function() {
  postman[Request]({
    name: "All Products Copy",
    id: "45eb1224-4ede-42b9-ad7f-74c6b411dc0e",
    method: "GET",
    address: "{{baseUrl}}/products",
    post(response) {
      const jsonData = pm.response.json();

      pm.test("Status code is 200", () => pm.response.to.have.status(200));

      

      pm.test("Products array exists", () => {
        pm.expect(jsonData).to.have.property("products");
        pm.expect(jsonData.products).to.be.an("array");
      });

      pm.test("Products array is not empty", () => {
        pm.expect(jsonData.products.length).to.be.above(0);
      });

      pm.test("First product has required keys", () => {
        const firstProduct = jsonData.products[0];
        pm.expect(firstProduct).to.have.property("id");
        pm.expect(firstProduct).to.have.property("title");
        pm.expect(firstProduct).to.have.property("price");
        pm.expect(firstProduct).to.have.property("stock");
      });
      sleep(1);
    }
  });
 

  postman[Request]({
    name: "Product by Id Copy",
    id: "4e273d2e-325c-41a3-ace6-b9f38420409a",
    method: "GET",
    address: "{{baseUrl}}/products/{{productId}}",
    post(response) {
      const jsonData = pm.response.json();

      pm.test("Status code is 200", () => pm.response.to.have.status(200));

     

      const productSchema = {
        type: "object",
        required: ["id", "title", "description", "price", "stock", "category"],
        properties: {
          id: { type: "number" },
          title: { type: "string" },
          description: { type: "string" },
          price: { type: "number" },
          stock: { type: "number" },
          category: { type: "string" },
          discountPercentage: { type: "number" },
          rating: { type: "number" },
          brand: { type: "string" },
          thumbnail: { type: "string" },
          images: { type: "array" }
        },
        additionalProperties: true
      };

      pm.test("Product response schema is valid", () => {
        pm.response.to.have.jsonSchema(productSchema);
      });
      sleep(1);
    }
  });
  

  postman[Request]({
    name: "Search Products Copy",
    id: "49b33698-d650-46f8-9ed6-eef739df8a85",
    method: "GET",
    address: "{{baseUrl}}/products/search?q=phone",
    post(response) {
      pm.test("Status code is 200", () => {
        pm.response.to.have.status(200);
      });

     
      sleep(1);
    }
  });

}
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";

export function handleSummary(data) {
  return {
    "summary.html": htmlReport(data),
  };
}
