name: API Tests - Newman

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: |
          cd API-Postman
          newman run "DummyJson_postman_collection.json" \
            -e "DummyJSON Env.postman_environment.json"
